export const ALL_FIELDS = {
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  USER_NAME: "username",
  EMAIL: "email",
  BIRTHDAY: "birthday",
  GENDER: "gender",
  PASSWORD: "password",
  RE_PASSWORD: "re-password",
};

export const DEFAULT_VALUEES = {
  [ALL_FIELDS.FIRST_NAME]: "",
  [ALL_FIELDS.LAST_NAME]: "",
  [ALL_FIELDS.USER_NAME]: "",
  [ALL_FIELDS.EMAIL]: "",
  [ALL_FIELDS.PASSWORD]: "",
  [ALL_FIELDS.RE_PASSWORD]: "",
  [ALL_FIELDS.BIRTHDAY]: null,
  [ALL_FIELDS.GENDER]: "",
};

export const SIGN_UP_FIELDS = [
  ALL_FIELDS.FIRST_NAME,
  ALL_FIELDS.LAST_NAME,
  ALL_FIELDS.USER_NAME,
  ALL_FIELDS.EMAIL,
  ALL_FIELDS.PASSWORD,
  ALL_FIELDS.RE_PASSWORD,
  ALL_FIELDS.BIRTHDAY,
  ALL_FIELDS.GENDER,
];

export const LOGIN_FIELDS = [ALL_FIELDS.USER_NAME, ALL_FIELDS.PASSWORD];

export const EDIT_FIELDS = [
  ALL_FIELDS.FIRST_NAME,
  ALL_FIELDS.LAST_NAME,
  ALL_FIELDS.USER_NAME,
  ALL_FIELDS.EMAIL,
  ALL_FIELDS.BIRTHDAY,
  ALL_FIELDS.GENDER,
];

export const ADD_FIELDS = [
  ALL_FIELDS.FIRST_NAME,
  ALL_FIELDS.LAST_NAME,
  ALL_FIELDS.USER_NAME,
  ALL_FIELDS.EMAIL,
  ALL_FIELDS.PASSWORD,
  ALL_FIELDS.RE_PASSWORD,
  ALL_FIELDS.BIRTHDAY,
  ALL_FIELDS.GENDER,
];

export const PROFILE_FIELDS = [
  ALL_FIELDS.FIRST_NAME,
  ALL_FIELDS.LAST_NAME,
  ALL_FIELDS.USER_NAME,
  ALL_FIELDS.EMAIL,
  ALL_FIELDS.BIRTHDAY,
  ALL_FIELDS.GENDER,
];
